## Exploración de datos 'vehicles_us'

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

Cargamos el archivo CSV

In [2]:
df = pd.read_csv('../vehicles_us.csv')
df.head()

price  model_year           model  condition  cylinders fuel  odometer  \
0   9400      2011.0          bmw x5       good        6.0  gas  145000.0   
1  25500         NaN      ford f-150       good        6.0  gas   88705.0   
2   5500      2013.0  hyundai sonata   like new        4.0  gas  110000.0   
3   1500      2003.0      ford f-150       fair        8.0  gas       NaN   
4  14900      2017.0    chrysler 200  excellent        4.0  gas   80903.0   

  transmission    type paint_color  is_4wd date_posted  days_listed  
0    automatic     SUV         NaN     1.0  2018-06-23           19  
1    automatic  pickup       white     1.0  2018-10-19           50  
2    automatic   sedan         red     NaN  2019-02-07           79  
3    automatic  pickup         NaN     NaN  2019-03-22            9  
4    automatic   sedan       black     NaN  2019-04-02           28

Ajustamos algunas valores de las columans para que esten en un mejor formato

In [3]:
df['date_posted'] = pd.to_datetime(df['date_posted'])
df['model_year'] = df['model_year'].fillna(0)
df['model_year'] = df['model_year'].astype(int)

Exploramos la información del DataFrame.

In [4]:
df['price'].describe()

count     51525.000000
mean      12132.464920
std       10040.803015
min           1.000000
25%        5000.000000
50%        9000.000000
75%       16839.000000
max      375000.000000
Name: price, dtype: float64

In [5]:
df['cylinders'].unique()

array([ 6.,  4.,  8., nan,  5., 10.,  3., 12.])

In [6]:
model = df[df['model'] == np.nan]
model

Empty DataFrame
Columns: [price, model_year, model, condition, cylinders, fuel, odometer, transmission, type, paint_color, is_4wd, date_posted, days_listed]
Index: []

In [7]:
df['condition'].unique()

array(['good', 'like new', 'fair', 'excellent', 'salvage', 'new'],
      dtype=object)

In [8]:
df['cylinders'].unique()

array([ 6.,  4.,  8., nan,  5., 10.,  3., 12.])

In [9]:
df['fuel'].unique()

array(['gas', 'diesel', 'other', 'hybrid', 'electric'], dtype=object)

In [10]:
df['odometer'].describe()

count     43633.000000
mean     115553.461738
std       65094.611341
min           0.000000
25%       70000.000000
50%      113000.000000
75%      155000.000000
max      990000.000000
Name: odometer, dtype: float64

In [11]:
df['transmission'].unique()

array(['automatic', 'manual', 'other'], dtype=object)

In [12]:
df['type'].unique()

array(['SUV', 'pickup', 'sedan', 'truck', 'coupe', 'van', 'convertible',
       'hatchback', 'wagon', 'mini-van', 'other', 'offroad', 'bus'],
      dtype=object)

In [13]:
df['paint_color'].unique()

array([nan, 'white', 'red', 'black', 'blue', 'grey', 'silver', 'custom',
       'orange', 'yellow', 'brown', 'green', 'purple'], dtype=object)

In [14]:
df['is_4wd'].unique()

array([ 1., nan])

In [16]:
# Crear la gráfica de dispersión
fig = px.scatter(df, x='type', y='fuel', title='Gráfica de Dispersión de Tipo vs Combustible')

# Personalizar los puntos
fig.update_traces(marker=dict(size=10, color='salmon'))

# Mostrar la gráfica
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
# Crear el histograma con Plotly Express
fig = px.histogram(df, x='date_posted', title='Histograma de Fechas de Publicación')

# Mostrar el histograma
fig.show()


ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed